name = "jasaweb"
compatibility_date = "2025-11-15"
compatibility_flags = ["nodejs_compat"]

[site]
bucket = "./dist"

# KV namespace for session storage
[[kv_namespaces]]
binding = "SESSION"
id = "SESSION_ID"
preview_id = "SESSION_PREVIEW_ID"